import { OllamaClient } from "./ollamaClient";
import { OllamaOrchestratorSettings } from "./settings";

/**
 * A rolling, incrementally-updated digest of ONE chat session: a compact
 * narrative of what's been discussed so far, plus the current best read of
 * what the user is overall trying to accomplish in this chat. Unlike
 * TempMemoryEntry (a candidate fact awaiting a save/discard decision), this
 * is never shown to the user and never written to the vault — it's pure
 * scratch context that lets the LLM "remember" earlier turns even when the
 * raw message history sent with a request is capped for token-efficiency.
 */
export interface SessionSummary {
	sessionId: string;
	/** Compact narrative summary of the conversation so far. */
	summary: string;
	/** Current best read of what the user is overall trying to accomplish in this chat, revised (not just appended to) as the conversation clarifies or changes it. */
	userIntent: string;
	/**
	 * The literal (not model-paraphrased) text of the most recent turn.
	 * The narrative `summary` above is regenerated by an LLM merge call each
	 * turn, so it's a compact retelling, not a transcript — a query that
	 * depends on the *exact* wording of what was just asked or answered
	 * (e.g. "what did you just say?", a follow-up quoting a figure or name
	 * from the last answer) can lose precision to that paraphrase. Storing
	 * the raw last exchange alongside the summary keeps the most recent
	 * answering and querying available verbatim, at zero extra LLM cost.
	 */
	lastUserText: string;
	lastAssistantText: string;
	/** How many user/assistant turn-pairs have been folded in so far. */
	turnsSummarized: number;
	updatedAt: number;
}

export type ChatHistoryData = Record<string, SessionSummary>;

export function emptyChatHistoryData(): ChatHistoryData {
	return {};
}

function extractJson<T>(raw: string): T | null {
	const match = raw.match(/\{[\s\S]*\}/);
	if (!match) return null;
	try {
		return JSON.parse(match[0]) as T;
	} catch {
		return null;
	}
}

const UPDATE_PROMPT = (
	prevSummary: string,
	prevIntent: string,
	userText: string,
	assistantText: string
) => `You are maintaining a running digest of an ongoing chat conversation, updated one turn at a time.

Summary so far (may be empty, if this is the first turn):
${prevSummary || "(none yet)"}

Current read of what the user is overall trying to accomplish in this chat (may be empty):
${prevIntent || "(none yet)"}

New turn just exchanged:
User: ${userText}
Assistant: ${assistantText}

Update both fields to fold in this new turn:
- "summary": a compact, continuous narrative of the conversation so far (not a transcript) — keep it concise but preserve facts, decisions, names, and context that later turns might depend on. Remove nothing that's still relevant, but don't just append the new turn verbatim; integrate it.
- "userIntent": the user's current overall goal or what they're trying to accomplish in this chat, as best understood right now. If this turn clarifies, changes, or completes their intent, revise it rather than just appending the old one.

Respond with ONLY JSON: {"summary": "...", "userIntent": "..."}`;

/**
 * Keeps one SessionSummary per chat session, updated with a single cheap
 * merge call per turn (previous digest + this turn -> new digest) rather
 * than re-reading the whole transcript every time, the same incremental
 * pattern extendLayeredMemory uses for topic memories.
 */
export class ChatHistoryStore {
	constructor(
		private data: ChatHistoryData,
		private persist: () => Promise<void>
	) {}

	get(sessionId: string): SessionSummary | undefined {
		return this.data[sessionId];
	}

	/** Renders the digest as a couple of context blocks, or undefined if nothing's been summarized yet. */
	contextBlock(sessionId: string): string | undefined {
		const s = this.data[sessionId];
		if (!s || (!s.summary && !s.userIntent)) return undefined;
		const lines: string[] = [];
		if (s.summary) lines.push(`### Summary of this conversation so far\n${s.summary}`);
		if (s.userIntent) lines.push(`### What the user has been trying to accomplish in this chat\n${s.userIntent}`);
		if (s.lastUserText || s.lastAssistantText) {
			lines.push(
				`### Most recent exchange (verbatim, in case exact wording matters)\nUser: ${s.lastUserText || "(none)"}\nAssistant: ${s.lastAssistantText || "(none)"}`
			);
		}
		return lines.join("\n\n");
	}

	/** Short plain-text form for feeding into other small prompts (intent extraction, memory-command detection, ambiguity checks) without an extra JSON layer. */
	inlineText(sessionId: string): string | undefined {
		const s = this.data[sessionId];
		if (!s || (!s.summary && !s.userIntent)) return undefined;
		const parts: string[] = [];
		if (s.summary) parts.push(`Conversation so far: ${s.summary}`);
		if (s.userIntent) parts.push(`User's overall goal so far: ${s.userIntent}`);
		if (s.lastUserText || s.lastAssistantText) {
			parts.push(`Most recent exchange — User: ${s.lastUserText || "(none)"} | Assistant: ${s.lastAssistantText || "(none)"}`);
		}
		return parts.join("\n");
	}

	async update(
		sessionId: string,
		userText: string,
		assistantText: string,
		client: OllamaClient,
		settings: OllamaOrchestratorSettings
	): Promise<SessionSummary> {
		const prev = this.data[sessionId];
		const prompt = UPDATE_PROMPT(prev?.summary ?? "", prev?.userIntent ?? "", userText, assistantText);
		const raw = await client.generate(settings.summaryModel, prompt, { temperature: 0.2 });
		const parsed = extractJson<{ summary?: string; userIntent?: string }>(raw);

		const next: SessionSummary = {
			sessionId,
			// If the model call failed to parse, keep the previous digest rather
			// than losing it, and fall back to a plain append so the turn isn't
			// silently dropped from the running context.
			summary: parsed?.summary?.trim() || `${prev?.summary ?? ""}${prev?.summary ? " " : ""}${userText}`.trim(),
			userIntent: parsed?.userIntent?.trim() || prev?.userIntent || "",
			// Stored as-is (no LLM round trip) so the most recent question and
			// answer are always available verbatim, independent of how well
			// the narrative `summary` above captured them.
			lastUserText: userText,
			lastAssistantText: assistantText,
			turnsSummarized: (prev?.turnsSummarized ?? 0) + 1,
			updatedAt: Date.now(),
		};
		this.data[sessionId] = next;
		await this.persist();
		return next;
	}

	async clearSession(sessionId: string): Promise<void> {
		if (!this.data[sessionId]) return;
		delete this.data[sessionId];
		await this.persist();
	}

	async clearAll(): Promise<void> {
		for (const id of Object.keys(this.data)) delete this.data[id];
		await this.persist();
	}
}
